### ISSUE TITLE
missing gyp files when install by npm / yarn

### ISSUE THREAD

**Issue by tearsofphoenix** [IDWMaster/ntrujs#4]
When install the package by npm / yarn, the `binding_darwin.gyp`, `binding_linux.gyp`, `binding_windows.gyp` not downloaded, so the install will fail. And it not automatically 
clone `ntru-crypto` and run `build_ntru` script. Maybe consider to add auto-clone-build-install
script ?

**Comment by IDWMaster** [comment]
@tearsofphoenix This should be fixed now. Please verify that it works.

**Comment by tearsofphoenix** [comment]
@IDWMaster 
I'm using both mac OS & Ubuntu, seems not work on mac OS.

**Comment by IDWMaster** [comment]
It's likely due to missing binaries. I never built MacOS and Windows binaries. Perhaps I do need to add a clone/build script that can be executed automatically. I'll look into that this weekend if I have time. Or; if you wanted to write such a script, feel free to do so and send a pull request for that.

**Comment by tearsofphoenix** [comment]
Ok, I'll work on it.

**Comment by IDWMaster** [comment]
Thanks!
